### PR TITLE
verify hg.mozilla.org with bundled CA root

### PR DESCRIPTION
**Pull request by xry111**
Before this, make-ca does not verify the certificate of hg.mozilla.org
at all.  It makes sense as make-ca often runs on systems without trust
anchor.  But, a MIM can easily fake hg.mozilla.org and completely hijack
the trust anchor of a BLFS system.

To improve the situation, we ship the certificate of the CA root for
hg.mozilla.org (DigiCert Global Root CA) in the make-ca package, and use
it to verify hg.mozilla.org.

### CODE REVIEW

**Comment by renodr** [comment]
@djlucas can we get a review on this when you have some time? :)

**Comment by renodr** [comment]
@djlucas it's been a bit, can we get a review on this one please? I saw the other PR in #24 for .NET and Steam, and feel like submitting both and then cutting a new release might be a good idea.

**Comment by djlucas** [comment]
Finally got around to testing today and it works as expected.

**Review by djlucas — COMMENTED** [review]
Verified working as expected.

**Pull request merged**
